"""empty message

Revision ID: 31f50d2aa99b
Revises: 
Create Date: 2020-12-24 18:00:29.343256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31f50d2aa99b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('base_word', sa.String(length=100), nullable=False))
    op.add_column('word', sa.Column('translation_word', sa.String(length=100), nullable=False))
    op.drop_column('word', 'ru_word')
    op.drop_column('word', 'eng_word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('eng_word', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('word', sa.Column('ru_word', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('word', 'translation_word')
    op.drop_column('word', 'base_word')
    # ### end Alembic commands ###
